# Generated by Django 3.1.1 on 2020-09-12 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, help_text='SL uuid: string of 32 hex characters with four dashes interspersed', max_length=36, validators=[django.core.validators.RegexValidator('^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$')]),
        ),
    ]
