# Generated by Django 3.1.1 on 2020-09-13 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200912_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ksoccer_points',
            new_name='kcoins',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matches',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, help_text='SL uuid: string of 32 hex characters with four dashes interspersed', max_length=36, validators=[django.core.validators.RegexValidator('^[a-z0-9-]{36}$')]),
        ),
    ]
