# Generated by Django 3.1.1 on 2020-09-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200913_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User details'},
        ),
    ]
