# Generated by Django 3.1.1 on 2020-10-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200917_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Unknown', max_length=63),
            preserve_default=False,
        ),
    ]
