# Generated by Django 3.1.1 on 2020-10-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matches',
            field=models.IntegerField(default=0),
        ),
    ]
