# Generated by Django 3.1.1 on 2020-09-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerstat',
            name='stat_uuid',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
