# Generated by Django 3.1.1 on 2020-09-13 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soccer', '0002_auto_20200913_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerstat',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.match'),
        ),
        migrations.CreateModel(
            name='MatchParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=4)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
