# Generated by Django 3.1.1 on 2020-09-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_auto_20200913_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
