# Generated by Django 3.1.1 on 2020-09-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_match_competition_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
