version: '3'

services:
  app:
    build: .
    command: ["/app_entrypoint.sh"]
    volumes:
      - /var/log/kbackend:/kbackend/core/logs
      - /db:/kbackend/core/db
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
